CREATE TABLE "Customers" ( -- Table to hold customer info for online orders
  "customer_id" INT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Create unique internal identifier for each customer entry
  "name" text NOT NULL, -- Customer name
  "email" text UNIQUE, -- Optional customer email
  "phone_number" text UNIQUE -- Optional customer phone number
);

CREATE TABLE "Order_Status" ( -- Table to hold order status for orders
  "status_id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Create unique internal identifier for each order entry
  "status_name" varchar(20) NOT NULL -- Order status for each order entry ("pending", "in-progress", "completed", "canceled")
);

CREATE TABLE "Guest_Tables" ( -- Table to hold in-restaurant tables info
  "table_id" INT NOT NULL UNIQUE GENERATED BY DEFAULT PRIMARY KEY, -- Create unique internal identifier for each table entry
  "capacity" int NOT NULL, -- Table entry's maximum capacity
  "table_status" text NOT NULL -- Table status ("empty", "ready-to-order", "ready-to-pay")
);

CREATE TABLE "Orders" ( -- Table to hold orders
  "order_id" INT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Create unique identifier for each order entry
  "order_date" date NOT NULL, -- Date the order was entered
  "customer_id" int, -- Foreign key linking back to Customers.customer_id | Used for online reservations/orders
  "status_id" int NOT NULL, -- Foreign key linking back to Order_Status.status_id
  "order_type" varchar(20) NOT NULL, -- Method of ordering ("online", "in-house")
  "table_id" int -- Foreign key linking back to Guest_Tables.table_id | Used for in-house orders
);

CREATE TABLE "Menu_Items" ( -- Menu_Items
  "item_id" INT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Create unique internal identifier for each menu item
  "name" text NOT NULL UNIQUE, -- Items name
  "price" decimal(5,2) NOT NULL -- Items price
);

CREATE TABLE "Payments" ( -- Create a table named Payments
  "payment_id" INT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Create a unique internal identifier for each payment processed
  "amount" decimal(6,2) NOT NULL, -- Bill total
  "payment_date" date NOT NULL, -- Date payment was processed
  "payment_method" text NOT NULL, -- How the bill was paid ("cash", "credit", "debit", "dish-washing")
  "order_id" int UNIQUE NOT NULL -- Foreign key linking back to Orders.order_id
);

CREATE TABLE "Reservations" ( -- Table to hold reservations
  "reservation_id" INT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Create unique internal identifier for each reservation
  "reservation_time" timestamp NOT NULL, -- reservation time
  "reservation_date" date NOT NULL, -- reservation date
  "party_size" int NOT NULL, -- How many people in the reservation
  "customer_id" int NOT NULL, -- Foreign key linking back to Customers.customer_id
  "table_id" int -- Foreign key linking back to Guest_Tables.table_id
);

CREATE TABLE "Order_Items" ( -- Table to hold customer's order
  "order_id" int NOT NULL, -- Foreign key linking back to Orders.order_id
  "item_id" int NOT NULL, -- Foreign key linking back to Menu_Items.item_id
  "quantity" int NOT NULL, -- Amount of item ordered (item_id)
  PRIMARY KEY ("order_id", "item_id") -- Set order_id and item_id as a composite primary key
);

ALTER TABLE "Orders" ADD FOREIGN KEY ("customer_id") REFERENCES "Customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE; -- Links Orders "customer_id" to Customers "customer_id"

ALTER TABLE "Orders" ADD FOREIGN KEY ("status_id") REFERENCES "Order_Status" ("status_id") DEFERRABLE INITIALLY IMMEDIATE; -- Links Orders "status_id" to Order_Status  "status_id"

ALTER TABLE "Orders" ADD FOREIGN KEY ("table_id") REFERENCES "Guest_Tables" ("table_id") DEFERRABLE INITIALLY IMMEDIATE; -- Links Orders "table_id" to Guest_Tables "table_id"

ALTER TABLE "Payments" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE; -- Links Payments "order_id" to Orders "order_id"

ALTER TABLE "Reservations" ADD FOREIGN KEY ("customer_id") REFERENCES "Customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE; -- Links Reservations "customer_id" to Customers "customer_id"

ALTER TABLE "Reservations" ADD FOREIGN KEY ("table_id") REFERENCES "Guest_Tables" ("table_id") DEFERRABLE INITIALLY IMMEDIATE; -- Links Reservations "table_id" to Guest_Tables "table_id"

ALTER TABLE "Order_Items" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE; -- Links Order_Items "order_id" to Orders "order_id"

ALTER TABLE "Order_Items" ADD FOREIGN KEY ("item_id") REFERENCES "Menu_Items" ("item_id") DEFERRABLE INITIALLY IMMEDIATE; -- Links Order_Items "item_id" to Menu_Items "item_id"
