CREATE TABLE "Customers" (
  "customer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "email" text UNIQUE,
  "phone_number" text
);

CREATE TABLE "Order_Status" (
  "status_id" int PRIMARY KEY,
  "status_name" string UNIQUE
);

CREATE TABLE "Guest_Tables" (
  "table_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "capacity" int,
  "table_status" text
);

CREATE TABLE "Orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_date" date,
  "customer_id" int,
  "status_id" int,
  "order_type" varchar,
  "table_id" int
);

CREATE TABLE "Menu_Items" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "price" deciaml(10,2)
);

CREATE TABLE "Payments" (
  "payment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" decimal(10,2),
  "payment_date" date,
  "payment_method" text,
  "order_id" int UNIQUE
);

CREATE TABLE "Reservations" (
  "reservation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_time" date,
  "party_size" int,
  "customer_id" int,
  "table_id" int
);

CREATE TABLE "Order_Items" (
  "order_id" int,
  "item_id" int,
  "quantity" int,
  PRIMARY KEY ("order_id", "item_id")
);

ALTER TABLE "Orders" ADD FOREIGN KEY ("customer_id") REFERENCES "Customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Orders" ADD FOREIGN KEY ("status_id") REFERENCES "Order_Status" ("status_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Orders" ADD FOREIGN KEY ("table_id") REFERENCES "Guest_Tables" ("table_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Payments" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Reservations" ADD FOREIGN KEY ("customer_id") REFERENCES "Customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Reservations" ADD FOREIGN KEY ("table_id") REFERENCES "Guest_Tables" ("table_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Order_Items" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Order_Items" ADD FOREIGN KEY ("item_id") REFERENCES "Menu_Items" ("item_id") DEFERRABLE INITIALLY IMMEDIATE;
